# Cloudflare Pages configuration for Bun
name = "iiitm-leaderboard"
compatibility_date = "2024-10-10"

[build]
command = "bun run build"
cwd = "."
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "20"
BUN_VERSION = "latest"

[[pages_build_output_dir]]
directory = "dist"